#include <iostream>
#include "../src/pool_s4_int8.h"
#include "pool_s4_int8_test_data.h"

// Feeds a real int8-quantized C3 activation map (generated by
// generate_test_data_int8.py, via a Python-side chain through the real
// int8 C1 -> S2 -> C3 pipeline) through the INT8 max-pooling HLS kernel,
// and checks the result against the Python reference (plain np.max over
// int8 values -- no scale factor needed) EXACTLY -- integer equality,
// not a floating-point tolerance.
int main() {
    static ap_int<8> input[IN_H][IN_W][CHANNELS];
    static ap_int<8> output[OUT_H][OUT_W][CHANNELS];

    for (int r = 0; r < IN_H; r++)
        for (int c = 0; c < IN_W; c++)
            for (int ch = 0; ch < CHANNELS; ch++)
                input[r][c][ch] = input_data[r][c][ch];

    pool_s4_int8(input, output);

    int mismatches = 0;
    int max_abs_diff = 0;
    for (int r = 0; r < OUT_H; r++) {
        for (int c = 0; c < OUT_W; c++) {
            for (int ch = 0; ch < CHANNELS; ch++) {
                int actual = output[r][c][ch].to_int();
                int expected = expected_output[r][c][ch];
                int diff = actual - expected;
                if (diff < 0) diff = -diff;
                if (diff > max_abs_diff) max_abs_diff = diff;
                if (actual != expected) {
                    if (mismatches < 10) {
                        std::cout << "Mismatch at [" << r << "][" << c << "][" << ch
                                  << "]: expected " << expected << ", got " << actual << std::endl;
                    }
                    mismatches++;
                }
            }
        }
    }

    std::cout << "Total output elements: " << (OUT_H * OUT_W * CHANNELS) << std::endl;
    std::cout << "Mismatches: " << mismatches << std::endl;
    std::cout << "Max abs diff: " << max_abs_diff << std::endl;

    if (mismatches == 0) {
        std::cout << "TEST PASSED -- HLS INT8 pool_s4 output matches Python int8 reference exactly" << std::endl;
        return 0;
    } else {
        std::cout << "TEST FAILED" << std::endl;
        return 1;
    }
}
