#include <iostream>
#include <cmath>
#include "../src/dense_output_int8.h"
#include "dense_output_int8_test_data.h"

// Feeds real int8-quantized Output-layer weights and a real
// int8-quantized F6 activation vector (generated by
// generate_test_data_int8.py, via the full C1->S2->C3->S4->flatten->
// C5->F6 int8 pipeline) through the INT8 HLS kernel, and checks the
// result against the Python reference.
//
// Stage 1 (the int8 MAC accumulation) is genuine integer arithmetic and
// was already verified bit-exact in Python (accumulator recovery
// assert, see the generator script) -- HLS computes the identical
// int32 accumulator deterministically, so any mismatch here beyond
// float rounding would show up as a large discrepancy, not a small one.
// Stage 2 (softmax) is intentionally float, so this check uses a tight
// numerical tolerance rather than exact equality -- the same standard
// this project's own float32 dense_output_tb.cpp and the top-level
// lenet5_top_tb.cpp already use for softmax output (std::exp()'s
// implementation and summation order can differ trivially from NumPy's).
int main() {
    static ap_int<8>  input[N_IN];
    static ap_int<8>  weights[N_IN][N_OUT];
    static ap_int<32> bias[N_OUT];
    static float      output[N_OUT];

    for (int i = 0; i < N_IN; i++)
        input[i] = input_data[i];

    for (int i = 0; i < N_IN; i++)
        for (int j = 0; j < N_OUT; j++)
            weights[i][j] = weights_data[i][j];

    for (int j = 0; j < N_OUT; j++)
        bias[j] = bias_int_data[j];

    dense_output_int8(input, weights, bias, X_SCALE, W_SCALE, output);

    float max_abs_diff = 0.0f;
    float sum = 0.0f;
    int predicted = 0;
    for (int j = 0; j < N_OUT; j++) {
        float diff = std::fabs(output[j] - expected_output[j]);
        if (diff > max_abs_diff) max_abs_diff = diff;
        sum += output[j];
        if (output[j] > output[predicted]) predicted = j;
        std::cout << "output[" << j << "] = " << output[j]
                   << "  (expected " << expected_output[j] << ")" << std::endl;
    }

    std::cout << "Sum of outputs: " << sum << std::endl;
    std::cout << "Predicted label: " << predicted << " (true label: " << TRUE_LABEL << ")" << std::endl;
    std::cout << "Max abs diff vs. Python reference: " << max_abs_diff << std::endl;

    bool pass = (max_abs_diff < 1e-5f) && (std::fabs(sum - 1.0f) < 1e-5f) && (predicted == TRUE_LABEL);

    if (pass) {
        std::cout << "TEST PASSED -- HLS INT8 Output softmax matches Python reference within tolerance" << std::endl;
        return 0;
    } else {
        std::cout << "TEST FAILED" << std::endl;
        return 1;
    }
}
