#include <iostream>
#include <cmath>
#include "../src/dense_output_int8_fixedpoint.h"
#include "dense_output_int8_fixedpoint_test_data.h"

// Feeds real int8-quantized Output weights and a real int8-quantized F6
// activation vector (generated by generate_test_data_int8_fixedpoint.py,
// via the C1->S2->C3->S4->C5->F6 int8 pipeline) through the two-stage
// fixed-point/float INT8 HLS kernel, and checks the result against the
// Python reference.
//
// Unlike C5's/F6's testbenches, this is NOT an exact integer-equality
// check: Stage 1's int32 accumulator is bit-exact by construction (same
// discipline as every earlier INT8 stage -- verified independently in
// the generator script), but Stage 2's softmax is genuine float32 math,
// and NumPy's vectorized exp() vs. C++'s scalar std::exp() can disagree
// by a few ULPs. So this compares against a tight absolute tolerance
// instead, and separately confirms the output is a valid probability
// distribution (sums to 1, matches the true predicted class).
int main() {
    static ap_int<8>  input[N_IN];
    static ap_int<8>  weights[N_IN][N_OUT];
    static ap_int<32> bias[N_OUT];
    static float       output[N_OUT];

    for (int i = 0; i < N_IN; i++)
        input[i] = input_data[i];

    for (int i = 0; i < N_IN; i++)
        for (int j = 0; j < N_OUT; j++)
            weights[i][j] = weights_data[i][j];

    for (int j = 0; j < N_OUT; j++)
        bias[j] = bias_int_data[j];

    dense_output_int8_fixedpoint(input, weights, bias, COMBINED_SCALE, output);

    const float TOLERANCE = 1e-5f;
    float max_abs_diff = 0.0f;
    int mismatches = 0;
    float sum_output = 0.0f;
    int predicted = 0;

    for (int j = 0; j < N_OUT; j++) {
        float diff = std::fabs(output[j] - expected_output[j]);
        if (diff > max_abs_diff) max_abs_diff = diff;
        if (diff > TOLERANCE) {
            if (mismatches < 10) {
                std::cout << "Mismatch at [" << j << "]: expected " << expected_output[j]
                          << ", got " << output[j] << " (diff " << diff << ")" << std::endl;
            }
            mismatches++;
        }
        sum_output += output[j];
        if (output[j] > output[predicted]) predicted = j;
    }

    std::cout << "Total output elements: " << N_OUT << std::endl;
    std::cout << "Mismatches (tolerance " << TOLERANCE << "): " << mismatches << std::endl;
    std::cout << "Max abs diff: " << max_abs_diff << std::endl;
    std::cout << "Sum of outputs: " << sum_output << " (expected ~1.0)" << std::endl;
    std::cout << "Predicted label: " << predicted << " (Python reference: " << PREDICTED_LABEL
              << ", true label: " << TRUE_LABEL << ")" << std::endl;

    bool sum_ok = std::fabs(sum_output - 1.0f) < 1e-4f;
    bool predicted_ok = (predicted == PREDICTED_LABEL);

    if (mismatches == 0 && sum_ok && predicted_ok) {
        std::cout << "TEST PASSED -- HLS int8 Output matches Python reference within tolerance, "
                     "sums to 1.0, and predicts the same class" << std::endl;
        return 0;
    } else {
        std::cout << "TEST FAILED" << std::endl;
        return 1;
    }
}
