"""
Generates lenet5_test_data.h: one real MNIST test image + the real trained
weights from Models/lenet5_relu.keras, plus the reference forward-pass
output computed with the project's own manual_layers.py (the same NumPy
reference manual_inference_relu.py uses), all embedded as C arrays for
lenet5_top_tb.cpp.

Loads the .keras archive directly via h5py instead of tf.keras.models.load_model
(TensorFlow isn't installed in this environment) -- a .keras file is just a
zip containing config.json + model.weights.h5, and the weight shapes alone
unambiguously identify which array belongs to which layer (no naming
ambiguity possible: conv layers differ by output-channel count, dense
layers by (N_in, N_out)).

MNIST test image comes from torchvision (also not TF-dependent) instead of
tf.keras.datasets.mnist -- both loaders serve the same canonical MNIST
binary test set in the same order, so test image 0 / label 7 here is
identical to what manual_inference_relu.py would load.

Run from repo root: python hls/lenet5_top/tb/generate_test_data.py
"""
import os
import sys
import zipfile
import tempfile

import numpy as np
import h5py
import torchvision

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "..", "src"))
from manual_layers import conv2d, maxpool2d, dense, relu

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..", "..", "..")
MODEL_PATH = os.path.join(REPO_ROOT, "Models", "lenet5_relu.keras")
OUT_PATH = os.path.join(os.path.dirname(__file__), "lenet5_test_data.h")

# ---- 1. Load trained weights straight out of the .keras archive ----
with tempfile.TemporaryDirectory() as tmpdir:
    with zipfile.ZipFile(MODEL_PATH) as z:
        z.extractall(tmpdir)
    with h5py.File(os.path.join(tmpdir, "model.weights.h5"), "r") as f:
        arrays = {}
        for group_name in f["layers"]:
            group = f["layers"][group_name]
            if "vars" not in group or len(group["vars"]) == 0:
                continue
            v = group["vars"]
            if len(v) >= 2:
                arrays[group_name] = (v["0"][()], v["1"][()])

# Map by shape, not by HDF5 group name (Keras v3 weight-file group names
# are generic ("conv2d", "dense", ...), not the model's own layer names).
c1_w = c1_b = c3_w = c3_b = c5_w = c5_b = f6_w = f6_b = out_w = out_b = None
for name, (w, b) in arrays.items():
    if w.shape == (5, 5, 1, 6):
        c1_w, c1_b = w, b
    elif w.shape == (5, 5, 6, 16):
        c3_w, c3_b = w, b
    elif w.shape == (400, 120):
        c5_w, c5_b = w, b
    elif w.shape == (120, 84):
        f6_w, f6_b = w, b
    elif w.shape == (84, 10):
        out_w, out_b = w, b

assert c1_w is not None and c3_w is not None and c5_w is not None
assert f6_w is not None and out_w is not None
print("Loaded weight shapes:")
print("  C1:", c1_w.shape, c1_b.shape)
print("  C3:", c3_w.shape, c3_b.shape)
print("  C5:", c5_w.shape, c5_b.shape)
print("  F6:", f6_w.shape, f6_b.shape)
print("  Output:", out_w.shape, out_b.shape)

# ---- 2. Load one real MNIST test image (test[0], same as tf.keras.datasets.mnist) ----
ds = torchvision.datasets.MNIST(root=os.path.join(tempfile.gettempdir(), "mnist_data"),
                                 train=False, download=True)
img_pil, true_label = ds[0]
image = (np.array(img_pil, dtype=np.float32) / 255.0).reshape(28, 28, 1)
print(f"\nTest image: MNIST test[0], true label = {true_label}")

# ---- 3. Reference forward pass -- identical math to manual_inference_relu.py ----
x = relu(conv2d(image, c1_w, c1_b, padding="same"))
x = maxpool2d(x, pool_size=2, stride=2)
x = relu(conv2d(x, c3_w, c3_b, padding="valid"))
x = maxpool2d(x, pool_size=2, stride=2)
x = x.flatten()
x = relu(dense(x, c5_w, c5_b, activation=None))
x = relu(dense(x, f6_w, f6_b, activation=None))
x = dense(x, out_w, out_b, activation="softmax")

predicted_label = int(np.argmax(x))
print(f"Reference predicted label = {predicted_label}, confidence = {x[predicted_label]*100:.2f}%")
print("Reference softmax output:", x)


def emit_array(f, name, dims, arr):
    flat = arr.astype(np.float32).flatten()
    dim_str = "".join(f"[{d}]" for d in dims)
    f.write(f"static const float {name}{dim_str} = {{\n")
    for i in range(0, len(flat), 8):
        chunk = flat[i:i + 8]
        f.write("    " + ", ".join(f"{v:.9e}f" for v in chunk) + ",\n")
    f.write("};\n\n")


with open(OUT_PATH, "w") as f:
    f.write("// AUTO-GENERATED by generate_test_data.py -- do not hand-edit.\n")
    f.write("// Real MNIST test[0] image + real Models/lenet5_relu.keras weights,\n")
    f.write("// plus the manual_layers.py reference forward-pass output, for\n")
    f.write("// lenet5_top_tb.cpp to check the full HLS chain against.\n")
    f.write("#ifndef LENET5_TEST_DATA_H\n#define LENET5_TEST_DATA_H\n\n")

    f.write(f"#define TRUE_LABEL {int(true_label)}\n")
    f.write(f"#define EXPECTED_CLASS {predicted_label}\n\n")

    emit_array(f, "test_image", [28, 28, 1], image)
    emit_array(f, "c1_weights_data", [5, 5, 1, 6], c1_w)
    emit_array(f, "c1_bias_data", [6], c1_b)
    emit_array(f, "c3_weights_data", [5, 5, 6, 16], c3_w)
    emit_array(f, "c3_bias_data", [16], c3_b)
    emit_array(f, "c5_weights_data", [400, 120], c5_w)
    emit_array(f, "c5_bias_data", [120], c5_b)
    emit_array(f, "f6_weights_data", [120, 84], f6_w)
    emit_array(f, "f6_bias_data", [84], f6_b)
    emit_array(f, "output_weights_data", [84, 10], out_w)
    emit_array(f, "output_bias_data", [10], out_b)
    emit_array(f, "expected_output", [10], x)

    f.write("#endif\n")

print(f"\nWrote {OUT_PATH}")
