#include <iostream>
#include "../src/dense_f6_int8_fixedpoint.h"
#include "dense_f6_int8_fixedpoint_test_data.h"

// Feeds real int8-quantized F6 weights and a real int8-quantized C5
// activation vector (generated by generate_test_data_int8_fixedpoint.py,
// via the full C1->S2->C3->S4->flatten->C5 int8 pipeline) through the
// fixed-point INT8 HLS kernel, and checks the result against the Python
// fixed-point reference (F6's OWN independently-derived M/S, verified
// accumulator recovery, genuine int64 multiply + rounding right-shift --
// see the generator script) EXACTLY -- integer equality, not a
// floating-point tolerance.
int main() {
    static ap_int<8>  input[N_IN];
    static ap_int<8>  weights[N_IN][N_OUT];
    static ap_int<32> bias[N_OUT];
    static ap_int<8>  output[N_OUT];

    for (int i = 0; i < N_IN; i++)
        input[i] = input_data[i];

    for (int i = 0; i < N_IN; i++)
        for (int j = 0; j < N_OUT; j++)
            weights[i][j] = weights_data[i][j];

    for (int j = 0; j < N_OUT; j++)
        bias[j] = bias_int_data[j];

    dense_f6_int8_fixedpoint(input, weights, bias, REQUANT_MULT, REQUANT_SHIFT, output);

    int mismatches = 0;
    int max_abs_diff = 0;
    for (int j = 0; j < N_OUT; j++) {
        int actual = output[j].to_int();
        int expected = expected_output[j];
        int diff = actual - expected;
        if (diff < 0) diff = -diff;
        if (diff > max_abs_diff) max_abs_diff = diff;
        if (actual != expected) {
            if (mismatches < 10) {
                std::cout << "Mismatch at [" << j << "]: expected " << expected
                          << ", got " << actual << std::endl;
            }
            mismatches++;
        }
    }

    std::cout << "Total output elements: " << N_OUT << std::endl;
    std::cout << "Mismatches: " << mismatches << std::endl;
    std::cout << "Max abs diff: " << max_abs_diff << std::endl;

    if (mismatches == 0) {
        std::cout << "TEST PASSED -- HLS fixed-point INT8 F6 output matches Python fixed-point reference exactly" << std::endl;
        return 0;
    } else {
        std::cout << "TEST FAILED" << std::endl;
        return 1;
    }
}
